from ._core import make_figure
import plotly.graph_objs as go

import matplotlib.pyplot as plt


def scatter(
        data_frame=None,
        x=None,
        y=None,
        color=None,
        symbol=None,
        size=None,
        hover_name=None,
        hover_data=None,
        custom_data=None,
        text=None,
        facet_row=None,
        facet_col=None,
        facet_col_wrap=0,
        facet_row_spacing=None,
        facet_col_spacing=None,
        error_x=None,
        error_x_minus=None,
        error_y=None,
        error_y_minus=None,
        animation_frame=None,
        animation_group=None,
        category_orders=None,
        labels=None,
        orientation=None,
        color_discrete_sequence=None,
        color_discrete_map=None,
        color_continuous_scale=None,
        range_color=None,
        color_continuous_midpoint=None,
        symbol_sequence=None,
        symbol_map=None,
        opacity=None,
        size_max=None,
        marginal_x=None,
        marginal_y=None,
        trendline=None,
        trendline_options=None,
        trendline_color_override=None,
        trendline_scope="trace",
        log_x=False,
        log_y=False,
        range_x=None,
        range_y=None,
        render_mode="auto",
        title=None,
        subtitle=None,
        template=None,
        width=None,
        height=None,
        *,
        sharex=True,
        sharey=True,
) -> plt.Figure:
    """
    In a scatter plot, each row of `data_frame` is represented by a symbol
    mark in 2D space.
    """
    return make_figure(args=locals(), constructor=go.Scatter)


def line(
        data_frame=None,
        x=None,
        y=None,
        line_group=None,
        color=None,
        line_dash=None,
        symbol=None,
        hover_name=None,
        hover_data=None,
        custom_data=None,
        text=None,
        facet_row=None,
        facet_col=None,
        facet_col_wrap=0,
        facet_row_spacing=None,
        facet_col_spacing=None,
        error_x=None,
        error_x_minus=None,
        error_y=None,
        error_y_minus=None,
        animation_frame=None,
        animation_group=None,
        category_orders=None,
        labels=None,
        orientation=None,
        color_discrete_sequence=None,
        color_discrete_map=None,
        line_dash_sequence=None,
        line_dash_map=None,
        symbol_sequence=None,
        symbol_map=None,
        markers=False,
        log_x=False,
        log_y=False,
        range_x=None,
        range_y=None,
        line_shape=None,
        render_mode="auto",
        title=None,
        subtitle=None,
        template=None,
        width=None,
        height=None,
        *,
        sharex=True,
        sharey=True,
) -> plt.Figure:
    """
    In a 2D line plot, each row of `data_frame` is represented as a vertex of
    a polyline mark in 2D space.
    """
    return make_figure(args=locals(), constructor=go.Scatter)


def bar(
        data_frame=None,
        x=None,
        y=None,
        color=None,
        pattern_shape=None,
        facet_row=None,
        facet_col=None,
        facet_col_wrap=0,
        facet_row_spacing=None,
        facet_col_spacing=None,
        hover_name=None,
        hover_data=None,
        custom_data=None,
        text=None,
        base=None,
        error_x=None,
        error_x_minus=None,
        error_y=None,
        error_y_minus=None,
        animation_frame=None,
        animation_group=None,
        category_orders=None,
        labels=None,
        color_discrete_sequence=None,
        color_discrete_map=None,
        color_continuous_scale=None,
        pattern_shape_sequence=None,
        pattern_shape_map=None,
        range_color=None,
        color_continuous_midpoint=None,
        opacity=None,
        orientation=None,
        barmode="relative",
        log_x=False,
        log_y=False,
        range_x=None,
        range_y=None,
        text_auto=False,
        title=None,
        subtitle=None,
        template=None,
        width=None,
        height=None,
        *,
        sharex=True,
        sharey=True,
) -> plt.Figure:
    """
    In a bar plot, each row of `data_frame` is represented as a rectangular
    mark.
    """
    return make_figure(
        args=locals(),
        constructor=go.Bar,
        trace_patch=dict(textposition="auto"),
        layout_patch=dict(barmode=barmode),
    )


def scatter_ternary(
        data_frame=None,
        a=None,
        b=None,
        c=None,
        color=None,
        symbol=None,
        size=None,
        text=None,
        hover_name=None,
        hover_data=None,
        custom_data=None,
        animation_frame=None,
        animation_group=None,
        category_orders=None,
        labels=None,
        color_discrete_sequence=None,
        color_discrete_map=None,
        color_continuous_scale=None,
        range_color=None,
        color_continuous_midpoint=None,
        symbol_sequence=None,
        symbol_map=None,
        opacity=None,
        size_max=None,
        title=None,
        subtitle=None,
        template=None,
        width=None,
        height=None,
) -> plt.Figure:
    """
    In a ternary scatter plot, each row of `data_frame` is represented by a
    symbol mark in ternary coordinates.
    """
    return make_figure(args=locals(), constructor=go.Scatterternary)
